spring.application.name=demo
spring.datasource.url=jdbc:postgresql://aws-1-ap-south-1.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=postgres.redcsqibijntscedgalv
spring.datasource.password=Zyd09286061150
spring.datasource.driver-class-name=org.postgresql.Driver
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=false
# Supabase does not expose the local H2 console
# spring.h2.console.enabled=true
# spring.h2.console.path=/h2-console
